# Generated by Django 2.1.7 on 2019-05-24 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('idPago', models.AutoField(primary_key=True, serialize=False)),
                ('montoPago', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fechaPago', models.DateField()),
                ('suscripcionPagada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suscripciones.Suscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('idTipoPago', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreTipoPago', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='tipoPagoRegistrado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.TipoPago'),
        ),
    ]
