# Generated by Django 2.1.7 on 2019-05-24 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(auto_now_add=True)),
                ('fechaCancelacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoSuscripcion',
            fields=[
                ('idTipoSuscripcion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcionTipoSuscripcion', models.CharField(max_length=200)),
                ('precioTipoSuscripcion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duracionTipoSuscripcion', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='suscripcionElegida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suscripciones.TipoSuscripcion'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='tiendaSuscripta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendas.Tienda'),
        ),
    ]
