# Generated by Django 2.1.7 on 2019-05-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='bio',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='face',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='imagenAdicional1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='imagenAdicional2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='imagenAdicional3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='imagenPrincipal',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='insta',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='mail',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='web',
            field=models.URLField(null=True),
        ),
    ]
