# Generated by Django 2.1.7 on 2019-06-04 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0004_tienda_nombretienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='categoriaTienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tiendas.Categoria'),
        ),
    ]
